# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1375, 953)
        MainWindow.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ecg_graph = QtWidgets.QWidget(self.frame_3)
        self.ecg_graph.setObjectName("ecg_graph")
        self.verticalLayout_2.addWidget(self.ecg_graph)
        self.eeg_graph = QtWidgets.QWidget(self.frame_3)
        self.eeg_graph.setObjectName("eeg_graph")
        self.verticalLayout_2.addWidget(self.eeg_graph)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("color: rgb(18, 255, 18);\n"
"font: 75 80pt \"Leelawadee UI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.spo2_value = QtWidgets.QLabel(self.frame_4)
        self.spo2_value.setStyleSheet("color: rgb(15, 255, 255);\n"
"font: 75 80pt \"Leelawadee UI\";")
        self.spo2_value.setAlignment(QtCore.Qt.AlignCenter)
        self.spo2_value.setObjectName("spo2_value")
        self.verticalLayout_4.addWidget(self.spo2_value)
        self.resp_value_2 = QtWidgets.QLabel(self.frame_4)
        self.resp_value_2.setStyleSheet("color: rgb(255, 255, 13);\n"
"font: 75 80pt \"Leelawadee UI\";")
        self.resp_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resp_value_2.setObjectName("resp_value_2")
        self.verticalLayout_4.addWidget(self.resp_value_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Leelawadee UI\";")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("font: 75 9pt \"Leelawadee UI\";\n"
"color: rgb(110, 110, 110);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("font: 75 9pt \"Leelawadee UI\";\n"
"color: rgb(110, 110, 110);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        self.label_10.setStyleSheet("font: 75 9pt \"Leelawadee UI\";\n"
"color: rgb(110, 110, 110);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setStyleSheet("font: 75 9pt \"Leelawadee UI\";\n"
"color: rgb(110, 110, 110);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_6.setStretch(4, 1)
        self.verticalLayout_6.setStretch(5, 1)
        self.horizontalLayout_3.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.temp_value = QtWidgets.QLabel(self.frame_13)
        self.temp_value.setStyleSheet("font: 75 30pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.temp_value.setObjectName("temp_value")
        self.verticalLayout_7.addWidget(self.temp_value)
        self.temp_value_2 = QtWidgets.QLabel(self.frame_13)
        self.temp_value_2.setStyleSheet("font: 75 30pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.temp_value_2.setObjectName("temp_value_2")
        self.verticalLayout_7.addWidget(self.temp_value_2)
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("color: rgb(18, 255, 18);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setStyleSheet("font: 75 16pt \"Leelawadee UI\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 13);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.horizontalLayout_3.addWidget(self.frame_14)
        self.frame_18 = QtWidgets.QFrame(self.frame_10)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setStyleSheet("color: rgb(255, 255, 13);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.resp_value = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resp_value.sizePolicy().hasHeightForWidth())
        self.resp_value.setSizePolicy(sizePolicy)
        self.resp_value.setStyleSheet("font: 75 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 13);")
        self.resp_value.setObjectName("resp_value")
        self.verticalLayout_12.addWidget(self.resp_value)
        self.horizontalLayout_3.addWidget(self.frame_18)
        self.frame_16 = QtWidgets.QFrame(self.frame_10)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("\n"
"color: rgb(232, 19, 19);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.ibp_value = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ibp_value.sizePolicy().hasHeightForWidth())
        self.ibp_value.setSizePolicy(sizePolicy)
        self.ibp_value.setStyleSheet("font: 75 16pt \"Leelawadee UI\";\n"
"\n"
"color: rgb(232, 19, 19);\n"
"")
        self.ibp_value.setObjectName("ibp_value")
        self.verticalLayout_10.addWidget(self.ibp_value)
        self.horizontalLayout_3.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setStyleSheet("color: rgb(15, 255, 255);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.co2_value = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.co2_value.sizePolicy().hasHeightForWidth())
        self.co2_value.setSizePolicy(sizePolicy)
        self.co2_value.setStyleSheet("font: 75 16pt \"Leelawadee UI\";\n"
"color: rgb(15, 255, 255);\n"
"")
        self.co2_value.setObjectName("co2_value")
        self.verticalLayout_13.addWidget(self.co2_value)
        self.horizontalLayout_3.addWidget(self.frame_19)
        self.frame_17 = QtWidgets.QFrame(self.frame_10)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_11.addWidget(self.label_19)
        self.nibp_value = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nibp_value.sizePolicy().hasHeightForWidth())
        self.nibp_value.setSizePolicy(sizePolicy)
        self.nibp_value.setStyleSheet("font: 75 16pt \"Leelawadee UI\";\n"
"color: rgb(110, 110, 110);\n"
"")
        self.nibp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.nibp_value.setObjectName("nibp_value")
        self.verticalLayout_11.addWidget(self.nibp_value)
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("\n"
"QLabel {\n"
"    font: bold 70px Arial; /* Large bold font */\n"
"    color: white; /* White text */\n"
"    text-shadow: 2px 2px 5px #444444; /* Shadow effect */\n"
"    background-color: transparent; /* No background */\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_15)
        self.label_16.setStyleSheet("QLabel {\n"
"    font: bold 20px Arial; /* Slightly smaller font */\n"
"    color: #999999; /* Gray text */\n"
"    text-shadow: 1px 1px 3px #444444; /* Lighter shadow */\n"
"    background-color: transparent; /* No background */\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.horizontalLayout_3.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unsilence_button = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unsilence_button.sizePolicy().hasHeightForWidth())
        self.unsilence_button.setSizePolicy(sizePolicy)
        self.unsilence_button.setMinimumSize(QtCore.QSize(0, 80))
        self.unsilence_button.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.unsilence_button.setObjectName("unsilence_button")
        self.horizontalLayout_2.addWidget(self.unsilence_button)
        self.silence_button = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.silence_button.sizePolicy().hasHeightForWidth())
        self.silence_button.setSizePolicy(sizePolicy)
        self.silence_button.setMinimumSize(QtCore.QSize(0, 80))
        self.silence_button.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.silence_button.setObjectName("silence_button")
        self.horizontalLayout_2.addWidget(self.silence_button)
        self.normal_btn = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal_btn.sizePolicy().hasHeightForWidth())
        self.normal_btn.setSizePolicy(sizePolicy)
        self.normal_btn.setMinimumSize(QtCore.QSize(0, 80))
        self.normal_btn.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.normal_btn.setObjectName("normal_btn")
        self.horizontalLayout_2.addWidget(self.normal_btn)
        self.tachy_btn = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tachy_btn.sizePolicy().hasHeightForWidth())
        self.tachy_btn.setSizePolicy(sizePolicy)
        self.tachy_btn.setMinimumSize(QtCore.QSize(0, 80))
        self.tachy_btn.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.tachy_btn.setObjectName("tachy_btn")
        self.horizontalLayout_2.addWidget(self.tachy_btn)
        self.brady_btn = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brady_btn.sizePolicy().hasHeightForWidth())
        self.brady_btn.setSizePolicy(sizePolicy)
        self.brady_btn.setMinimumSize(QtCore.QSize(0, 80))
        self.brady_btn.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.brady_btn.setObjectName("brady_btn")
        self.horizontalLayout_2.addWidget(self.brady_btn)
        self.afib_btn = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afib_btn.sizePolicy().hasHeightForWidth())
        self.afib_btn.setSizePolicy(sizePolicy)
        self.afib_btn.setMinimumSize(QtCore.QSize(0, 80))
        self.afib_btn.setStyleSheet("QPushButton {\n"
"    background-color: #333333;  /* Dark gray background */\n"
"    color: white;  /* White text */\n"
"    border-radius: 5px;  /* Rounded corners */\n"
"    border: 2px solid #222222;  /* Slightly darker border */\n"
"    padding: 8px 16px;  /* Padding for a better appearance */\n"
"    font: bold 14px Arial;  /* Bold text */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;  /* Slightly lighter gray when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;  /* Darker gray when pressed */\n"
"}\n"
"\n"
"QPushButton#alarmReset {\n"
"    background-color: #cccc00;  /* Yellow for Alarm Reset */\n"
"    color: black;\n"
"    border: 2px solid #aaaa00;\n"
"}\n"
"\n"
"QPushButton#alarmPause {\n"
"    background-color: #cc6600;  /* Orange for Alarm Pause */\n"
"    color: black;\n"
"    border: 2px solid #aa5500;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #555555;  /* Gray when disabled */\n"
"    color: #888888;\n"
"    border: 2px solid #444444;\n"
"}\n"
"")
        self.afib_btn.setObjectName("afib_btn")
        self.horizontalLayout_2.addWidget(self.afib_btn)
        self.frame_5 = QtWidgets.QFrame(self.frame_11)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pattern_value_2 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pattern_value_2.sizePolicy().hasHeightForWidth())
        self.pattern_value_2.setSizePolicy(sizePolicy)
        self.pattern_value_2.setStyleSheet("color: white;\n"
"font: 75 14pt \"Leelawadee UI\";")
        self.pattern_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pattern_value_2.setObjectName("pattern_value_2")
        self.horizontalLayout_5.addWidget(self.pattern_value_2)
        self.alarm_label = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarm_label.sizePolicy().hasHeightForWidth())
        self.alarm_label.setSizePolicy(sizePolicy)
        self.alarm_label.setStyleSheet("color: rgb(232, 19, 19);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.alarm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_label.setObjectName("alarm_label")
        self.horizontalLayout_5.addWidget(self.alarm_label)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pattern_value_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pattern_value_3.sizePolicy().hasHeightForWidth())
        self.pattern_value_3.setSizePolicy(sizePolicy)
        self.pattern_value_3.setStyleSheet("color: white;\n"
"font: 75 14pt \"Leelawadee UI\";")
        self.pattern_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.pattern_value_3.setObjectName("pattern_value_3")
        self.horizontalLayout_6.addWidget(self.pattern_value_3)
        self.pattern_value = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pattern_value.sizePolicy().hasHeightForWidth())
        self.pattern_value.setSizePolicy(sizePolicy)
        self.pattern_value.setStyleSheet("color: rgb(18, 255, 18);\n"
"font: 75 16pt \"Leelawadee UI\";")
        self.pattern_value.setAlignment(QtCore.Qt.AlignCenter)
        self.pattern_value.setObjectName("pattern_value")
        self.horizontalLayout_6.addWidget(self.pattern_value)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "80"))
        self.spo2_value.setText(_translate("MainWindow", "98"))
        self.resp_value_2.setText(_translate("MainWindow", "20"))
        self.label_6.setText(_translate("MainWindow", "T1"))
        self.label_9.setText(_translate("MainWindow", "38.0"))
        self.label_11.setText(_translate("MainWindow", "35.0"))
        self.label_5.setText(_translate("MainWindow", "T2"))
        self.label_10.setText(_translate("MainWindow", "38.0"))
        self.label_12.setText(_translate("MainWindow", "35.0"))
        self.temp_value.setText(_translate("MainWindow", "37.2"))
        self.temp_value_2.setText(_translate("MainWindow", "37.4°C"))
        self.label_13.setText(_translate("MainWindow", "HR"))
        self.label_14.setText(_translate("MainWindow", "80"))
        self.label_21.setText(_translate("MainWindow", "RR"))
        self.resp_value.setText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "IBP"))
        self.ibp_value.setText(_translate("MainWindow", "98"))
        self.label_18.setText(_translate("MainWindow", "CO2"))
        self.co2_value.setText(_translate("MainWindow", "98"))
        self.label_19.setText(_translate("MainWindow", "NIBP"))
        self.nibp_value.setText(_translate("MainWindow", "98"))
        self.label_15.setText(_translate("MainWindow", "120/80 "))
        self.label_16.setText(_translate("MainWindow", "( 93)"))
        self.unsilence_button.setText(_translate("MainWindow", "Alarm Reset"))
        self.silence_button.setText(_translate("MainWindow", "Alarm Pause"))
        self.normal_btn.setText(_translate("MainWindow", "normal"))
        self.tachy_btn.setText(_translate("MainWindow", "tachy"))
        self.brady_btn.setText(_translate("MainWindow", "brady"))
        self.afib_btn.setText(_translate("MainWindow", "afib"))
        self.pattern_value_2.setText(_translate("MainWindow", "Alarm State:"))
        self.alarm_label.setText(_translate("MainWindow", "Alarms Label"))
        self.pattern_value_3.setText(_translate("MainWindow", "Patient State:"))
        self.pattern_value.setText(_translate("MainWindow", "pattern Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
